name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make CC=gcc
      run: make CC=gcc
    - name: make CC=clang
      run: make CC=clang
    - name: make BUILD=release CC=gcc
      run: make BUILD=release CC=gcc
    - name: make BUILD=release CC=clang
      run: make BUILD=release CC=clang
